### ISSUE TITLE
Error writing to file

### ISSUE THREAD

**Issue by AuYuHui** [JeffreyCA/spleeter-web#1218]
![image](https://github.com/user-attachments/assets/ccb84195-9bbb-4aa6-99ea-a75d003fb5c4)
![image](https://github.com/user-attachments/assets/fdcef372-c8a7-40dd-b8a1-e9268bb6f520)
![image](https://github.com/user-attachments/assets/47b08624-6c73-4223-83cf-a8d48648ecc0)

**Comment by AuYuHui** [comment]
![image](https://github.com/user-attachments/assets/e0ffdffd-3b4e-4721-b1d3-892f2723a4b5)

**Comment by JeffreyCA** [comment]
Can you try using the [test branch](https://github.com/JeffreyCA/spleeter-web/tree/test)?

And can you check if this is the same issue: https://stackoverflow.com/questions/70148547/wsl2-pytorch-runtimeerror-no-cuda-gpus-are-available-with-rtx3080

**Comment by AuYuHui** [comment]
> Can you try using the [test branch](https://github.com/JeffreyCA/spleeter-web/tree/test)?
> 
> And can you check if this is the same issue: https://stackoverflow.com/questions/70148547/wsl2-pytorch-runtimeerror-no-cuda-gpus-are-available-with-rtx3080

![Image](https://github.com/user-attachments/assets/841d1c35-61a4-4355-8a90-8171db60a166)


try test branch

**Comment by JeffreyCA** [comment]
> > Can you try using the [test branch](https://github.com/JeffreyCA/spleeter-web/tree/test)?
> > And can you check if this is the same issue: https://stackoverflow.com/questions/70148547/wsl2-pytorch-runtimeerror-no-cuda-gpus-are-available-with-rtx3080
> 
> ![Image](https://github.com/user-attachments/assets/841d1c35-61a4-4355-8a90-8171db60a166)
> 
> try test branch

What GPU are you using, and are you using the latest drivers?

**Comment by AuYuHui** [comment]
![Image](https://github.com/user-attachments/assets/d1561ac9-a0f2-43f0-b845-6ae267f1b067)

**Comment by AuYuHui** [comment]
elery-slow-1  | [2025-05-13 13:55:07,172: WARNING/MainProcess] /usr/local/lib/python3.9/dist-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
celery-slow-1  | whether broker connection retries are made during startup in Celery 6.0 and above.
celery-slow-1  | If you wish to retain the existing behavior for retrying connections on startup,
celery-slow-1  | you should set broker_connection_retry_on_startup to True.
celery-slow-1  |   warnings.warn(
celery-slow-1  | 
celery-slow-1  | [2025-05-13 13:55:07,181: INFO/MainProcess] Connected to redis://redis:6379/0
celery-slow-1  | [2025-05-13 13:55:07,181: WARNING/MainProcess] /usr/local/lib/python3.9/dist-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
celery-slow-1  | whether broker connection retries are made during startup in Celery 6.0 and above.
celery-slow-1  | If you wish to retain the existing behavior for retrying connections on startup,
celery-slow-1  | you should set broker_connection_retry_on_startup to True.
celery-slow-1  |   warnings.warn(
celery-slow-1  | 
celery-slow-1  | [2025-05-13 13:55:07,185: INFO/MainProcess] mingle: searching for neighbors
celery-slow-1  | [2025-05-13 13:55:07,188: CRITICAL/MainProcess] Unrecoverable error: EncodeError(TypeError('keys must be str, int, float, bool or None, not UUID'))
celery-slow-1  | Traceback (most recent call last):
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/serialization.py", line 41, in _reraise_errors
celery-slow-1  |     yield
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/serialization.py", line 220, in dumps
celery-slow-1  |     payload = encoder(data)
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/utils/json.py", line 63, in dumps
celery-slow-1  |     return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
celery-slow-1  |   File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
celery-slow-1  |     return cls(
celery-slow-1  |   File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
celery-slow-1  |     chunks = self.iterencode(o, _one_shot=True)
celery-slow-1  |   File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
celery-slow-1  |     return _iterencode(o, 0)
celery-slow-1  | TypeError: keys must be str, int, float, bool or None, not UUID
celery-slow-1  | 
celery-slow-1  | During handling of the above exception, another exception occurred:
celery-slow-1  | 
celery-slow-1  | Traceback (most recent call last):
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/celery/worker/worker.py", line 202, in start
celery-slow-1  |     self.blueprint.start(self)
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/celery/bootsteps.py", line 116, in start
celery-slow-1  |     step.start(parent)
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/celery/bootsteps.py", line 365, in start
celery-slow-1  |     return self.obj.start()
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/celery/worker/consumer/consumer.py", line 340, in start
celery-slow-1  |     blueprint.start(self)
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/celery/bootsteps.py", line 116, in start
celery-slow-1  |     step.start(parent)
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/celery/worker/consumer/mingle.py", line 37, in start
celery-slow-1  |     self.sync(c)
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/celery/worker/consumer/mingle.py", line 41, in sync
celery-slow-1  |     replies = self.send_hello(c)
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/celery/worker/consumer/mingle.py", line 54, in send_hello
celery-slow-1  |     replies = inspect.hello(c.hostname, our_revoked._data) or {}
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/celery/app/control.py", line 389, in hello
celery-slow-1  |     return self._request('hello', from_node=from_node, revoked=revoked)
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/celery/app/control.py", line 106, in _request
celery-slow-1  |     return self._prepare(self.app.control.broadcast(
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/celery/app/control.py", line 776, in broadcast
celery-slow-1  |     return self.mailbox(conn)._broadcast(
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/pidbox.py", line 337, in _broadcast
celery-slow-1  |     self._publish(command, arguments, destination=destination,
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/pidbox.py", line 305, in _publish
celery-slow-1  |     producer.publish(
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/messaging.py", line 175, in publish
celery-slow-1  |     body, content_type, content_encoding = self._prepare(
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/messaging.py", line 268, in _prepare
celery-slow-1  |     body) = dumps(body, serializer=serializer)
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/serialization.py", line 220, in dumps
celery-slow-1  |     payload = encoder(data)
celery-slow-1  |   File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
celery-slow-1  |     self.gen.throw(type, value, traceback)
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/serialization.py", line 45, in _reraise_errors
celery-slow-1  |     reraise(wrapper, wrapper(exc), sys.exc_info()[2])
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/exceptions.py", line 34, in reraise
celery-slow-1  |     raise value.with_traceback(tb)
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/serialization.py", line 41, in _reraise_errors
celery-slow-1  |     yield
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/serialization.py", line 220, in dumps
celery-slow-1  |     payload = encoder(data)
celery-slow-1  |   File "/usr/local/lib/python3.9/dist-packages/kombu/utils/json.py", line 63, in dumps
celery-slow-1  |     return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
celery-slow-1  |   File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
celery-slow-1  |     return cls(
celery-slow-1  |   File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
celery-slow-1  |     chunks = self.iterencode(o, _one_shot=True)
celery-slow-1  |   File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
celery-slow-1  |     return _iterencode(o, 0)
celery-slow-1  | kombu.exceptions.EncodeError: keys must be str, int, float, bool or None, not UUID
celery-fast-1  | 2025-05-13 13:55:07,529 [nnabla][INFO]: Initializing CPU extension...

**Comment by JeffreyCA** [comment]
Are you using the latest `master` branch? Can you try building from source?

1. `git checkout master`
2. `git pull`
3. `docker compose -f docker-compose.gpu.yml -f docker-compose.build.gpu.yml -f docker-compose.prod.yml -f docker-compose.prod.selfhost.yml up --build`

**Comment by DMB-codegang** [comment]
I noticed this issue in the logs:
`torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device`
I checked with an AI, and it said that the PyTorch version is compiled for newer GPU architectures sm_70 and above, but I'm using a Tesla P4, which is Pascal architecture (sm_61). PyTorch 2.1+ has completely removed support for sm_61, so I must use PyTorch <= 2.0.1. Will using this version affect the operation of this project?

我注意到日志报了这个问题：
`torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device`
我使用ai查询了一下，ai说PyTorch 版本是为sm_70 及以上的较新的 GPU 架构编译的，但我使用的是Tesla P4 是 Pascal 架构 (sm_61)。PyTorch 2.1+ 已完全移除 sm_61 支持。必须使用 PyTorch <= 2.0.1。使用这个版本会影响本项目的运行吗

**Comment by JeffreyCA** [comment]
> I noticed this issue in the logs: `torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device` I checked with an AI, and it said that the PyTorch version is compiled for newer GPU architectures sm_70 and above, but I'm using a Tesla P4, which is Pascal architecture (sm_61). PyTorch 2.1+ has completely removed support for sm_61, so I must use PyTorch <= 2.0.1. Will using this version affect the operation of this project?
> 
> 我注意到日志报了这个问题： `torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device` 我使用ai查询了一下，ai说PyTorch 版本是为sm_70 及以上的较新的 GPU 架构编译的，但我使用的是Tesla P4 是 Pascal 架构 (sm_61)。PyTorch 2.1+ 已完全移除 sm_61 支持。必须使用 PyTorch <= 2.0.1。使用这个版本会影响本项目的运行吗

Unfortunately the latest version likely doesn't support it. You can try running `v3.20.2`, which uses [PyTorch 1.13.1](https://github.com/JeffreyCA/spleeter-web/blob/v3.20.2/gpu.Dockerfile#L33):

```
TAG=v3.20.2 docker compose -f docker-compose.gpu.yml -f docker-compose.prod.yml -f docker-compose.prod.selfhost.yml up
```

However it won't have some of the newer models, fixes, etc.
