### ISSUE TITLE
get_file_ext failed

### ISSUE THREAD

**Issue by keyosuke** [JeffreyCA/spleeter-web#96]
The YouTube search feature still seems to work, but the download from YouTube seems to fail.  I think some underlying conversion service this was relying on must have gone down.  If I upload an mp3, the audio is split into parts, with only the conversion from YouTube failing.  

![image](https://user-images.githubusercontent.com/795074/135782256-f4f0e14f-669f-4fcb-bfff-dda38621a866.png)

**Comment by keyosuke** [comment]
Just another screenshot showing what happens if you paste the same YouTube video URL in rather than search by terms, which is what the screenshot above was of. 
![image](https://user-images.githubusercontent.com/795074/135782438-0fc9bd01-2bed-4d89-a577-f38097a3857e.png)

**Comment by JeffreyCA** [comment]
Thanks for filing this issue. Is it just this particular YouTube link that's causing issues? Can you access the link itself normally?

Do the logs from the Celery process indicate any errors?

**Comment by keyosuke** [comment]
Is it just this particular YouTube link that's causing issues?  No.  It's
most or all of them.  I vaguely remember one of them working, a week ago,
but I could have been mistaken.

Can you access the link itself normally?  Yes.
https://www.youtube.com/watch?v=UPO-pcJnL-0  plays like a charm.

Do the logs from the Celery process indicate any errors?

Celery Fast When Entering “https://www.youtube.com/watch?v=UPO-pcJnL-0” in
search

[2021-10-04 01:44:51,286: WARNING/ForkPoolWorker-1] ERROR: Unable to
download API page: <urlopen error [Errno 99] Cannot assign requested
address> (caused by URLError(OSError(99, 'Cannot assign requested
address')))

[2021-10-04 01:44:51,286: WARNING/ForkPoolWorker-1] get_file_ext failed

[2021-10-04 01:44:51,302: ERROR/ForkPoolWorker-1] Task
api.tasks.fetch_youtube_audio[49a86d64-8761-4e03-bf20-f8997b2c5fc9] raised
unexpected: Exception('get_file_ext failed')

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line
450, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line
731, in __protected_call__

    return self.run(*args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/celery/app/autoretry.py",
line 54, in run

    ret = task.retry(exc=exc, **retry_kwargs)

  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line
714, in retry

    raise_with_context(exc)

  File "/usr/local/lib/python3.7/site-packages/celery/app/autoretry.py",
line 34, in run

    return task._orig_run(*args, **kwargs)

  File "/webapp/api/tasks.py", line 281, in fetch_youtube_audio

    raise error

  File "/webapp/api/tasks.py", line 240, in fetch_youtube_audio

    title) + get_file_ext(link)

  File "/webapp/api/youtubedl.py", line 37, in get_file_ext

    raise Exception('get_file_ext failed')

Exception: get_file_ext failed


Celery Fast when selecting video from search terms “Toad the wet sprocket
fever”, clicking first result, then clicking Finish.


1] ERROR: Unable to download API page: <urlopen error [Errno 99] Cannot
assign requested address> (caused by URLError(OSError(99, 'Cannot assign
requested address')))

[2021-10-04 06:06:35,260: WARNING/ForkPoolWorker-1] get_file_ext failed

[2021-10-04 06:06:35,271: ERROR/ForkPoolWorker-1] Task
api.tasks.fetch_youtube_audio[e905f8b0-f189-449b-b58f-edaabb6b5ed1] raised
unexpected: Exception('get_file_ext failed')

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line
450, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line
731, in __protected_call__

    return self.run(*args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/celery/app/autoretry.py",
line 54, in run

    ret = task.retry(exc=exc, **retry_kwargs)

  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line
714, in retry

    raise_with_context(exc)

  File "/usr/local/lib/python3.7/site-packages/celery/app/autoretry.py",
line 34, in run

    return task._orig_run(*args, **kwargs)

  File "/webapp/api/tasks.py", line 281, in fetch_youtube_audio

    raise error

  File "/webapp/api/tasks.py", line 240, in fetch_youtube_audio

    title) + get_file_ext(link)

  File "/webapp/api/youtubedl.py", line 37, in get_file_ext

    raise Exception('get_file_ext failed')

Exception: get_file_ext failed

**Comment by JeffreyCA** [comment]
Thanks. This looks like something with your network configuration not playing well with Docker. Not something I'm very familiar with. Are you running any other containers that may conflict with Spleeter Web?

Maybe try this?

https://eabahurire.medium.com/oserror-errno-99-cannot-assign-requested-address-when-starting-dockerized-web-app-54c11f7041ea

**Comment by keyosuke** [comment]
Well, I'm glad it's not affecting anyone else using this.  I have no other
dockers running.  I just set this up, used it for a month or so without any
issues, and then the issue.  Beats me.  My PC is connected to a cable modem
via a wired router that supports uPNP.  I'm not sure if this Docker
container uses uPNP for any routing.  I guess I'll blow it away and
reinstall to see if whatever the issue is goes away.

**Comment by JeffreyCA** [comment]
What OS are you running?

**Comment by keyosuke** [comment]
Microsoft Windows [Version 10.0.19043.1237] Professional edition.

**Comment by JeffreyCA** [comment]
I can reproduce the error on a Windows VM, looking into it.
